version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    hostname: timescaledb
    container_name: timescaledb
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: aquapp_user
      POSTGRES_PASSWORD: h5shx4jtEwSCpXhLn7W
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

volumes:
  timescaledb_data: