// <auto-generated />
using System;
using AquaPP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AquaPP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("AquaPP.Core.Models.IoT.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("SensorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ThresholdValue")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("TriggerValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Acknowledged");

                    b.HasIndex("SensorId");

                    b.HasIndex("Severity");

                    b.HasIndex("Timestamp");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("AquaPP.Core.Models.IoT.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("InstallationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("AquaPP.Core.Models.IoT.Reading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SensorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("SensorId", "Timestamp");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("AquaPP.Core.Models.IoT.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SamplingIntervalMs")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ThresholdHigh")
                        .HasColumnType("REAL");

                    b.Property<double?>("ThresholdLow")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Type");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("AquaPP.Core.Models.IoT.Alert", b =>
                {
                    b.HasOne("AquaPP.Core.Models.IoT.Sensor", "Sensor")
                        .WithMany("Alerts")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("AquaPP.Core.Models.IoT.Reading", b =>
                {
                    b.HasOne("AquaPP.Core.Models.IoT.Sensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("AquaPP.Core.Models.IoT.Sensor", b =>
                {
                    b.HasOne("AquaPP.Core.Models.IoT.Asset", "Asset")
                        .WithMany("Sensors")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AquaPP.Core.Models.IoT.Asset", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("AquaPP.Core.Models.IoT.Sensor", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
