// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moondesk.DataAccess.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Moondesk.DataAccess.Migrations
{
    [DbContext(typeof(MoondeskDbContext))]
    [Migration("20251119172604_UpdatedExtendedModels")]
    partial class UpdatedExtendedModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Moondesk.Domain.Models.IoT.Alert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("boolean")
                        .HasColumnName("acknowledged");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("acknowledged_by");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .HasColumnType("hstore")
                        .HasColumnName("metadata");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("notes");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer")
                        .HasColumnName("protocol");

                    b.Property<long>("SensorId")
                        .HasColumnType("bigint")
                        .HasColumnName("sensor_id");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<double?>("ThresholdValue")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold_value");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<double>("TriggerValue")
                        .HasColumnType("double precision")
                        .HasColumnName("trigger_value");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("ix_alerts_sensor_id");

                    b.HasIndex("OrganizationId", "Acknowledged", "Timestamp")
                        .HasDatabaseName("ix_alerts_organization_id_acknowledged_timestamp");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("Moondesk.Domain.Models.IoT.Asset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("InstallationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installation_date");

                    b.Property<DateTimeOffset?>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("manufacturer");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .HasColumnType("hstore")
                        .HasColumnName("metadata");

                    b.Property<string>("ModelNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_assets_organization_id");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("Moondesk.Domain.Models.IoT.Command", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("command_type");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("max_retries");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .IsRequired()
                        .HasColumnType("hstore")
                        .HasColumnName("metadata");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Response")
                        .HasColumnType("text")
                        .HasColumnName("response");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<long>("SensorId")
                        .HasColumnType("bigint")
                        .HasColumnName("sensor_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_commands");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("ix_commands_sensor_id");

                    b.HasIndex("OrganizationId", "UserId")
                        .HasDatabaseName("ix_commands_organization_id_user_id");

                    b.HasIndex("OrganizationId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_commands_organization_id_status_created_at");

                    b.ToTable("commands", (string)null);
                });

            modelBuilder.Entity("Moondesk.Domain.Models.IoT.Reading", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .HasColumnType("hstore")
                        .HasColumnName("metadata");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("organization_id");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer")
                        .HasColumnName("protocol");

                    b.Property<int>("Quality")
                        .HasColumnType("integer")
                        .HasColumnName("quality");

                    b.Property<long>("SensorId")
                        .HasColumnType("bigint")
                        .HasColumnName("sensor_id");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id", "Timestamp")
                        .HasName("pk_readings");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("ix_readings_sensor_id");

                    b.HasIndex("OrganizationId", "Timestamp")
                        .HasDatabaseName("IX_Readings_OrgId_Timestamp");

                    b.HasIndex("OrganizationId", "SensorId", "Timestamp")
                        .HasDatabaseName("IX_Readings_OrgId_SensorId_Timestamp");

                    b.ToTable("readings", (string)null);
                });

            modelBuilder.Entity("Moondesk.Domain.Models.IoT.Sensor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint")
                        .HasColumnName("asset_id");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("max_value");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .HasColumnType("hstore")
                        .HasColumnName("metadata");

                    b.Property<double?>("MinValue")
                        .HasColumnType("double precision")
                        .HasColumnName("min_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer")
                        .HasColumnName("protocol");

                    b.Property<int>("SamplingIntervalMs")
                        .HasColumnType("integer")
                        .HasColumnName("sampling_interval_ms");

                    b.Property<double?>("ThresholdHigh")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold_high");

                    b.Property<double?>("ThresholdLow")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold_low");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_sensors");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_sensors_asset_id");

                    b.HasIndex("OrganizationId", "AssetId")
                        .HasDatabaseName("ix_sensors_organization_id_asset_id");

                    b.HasIndex("OrganizationId", "IsActive")
                        .HasDatabaseName("ix_sensors_organization_id_is_active");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("Moondesk.Domain.Models.Network.ConnectionCredential", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientId")
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_password");

                    b.Property<string>("EncryptionIV")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encryption_iv");

                    b.Property<string>("EndpointUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint_uri");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer")
                        .HasColumnName("protocol");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_connection_credentials");

                    b.ToTable("connection_credentials", (string)null);
                });

            modelBuilder.Entity("Moondesk.Domain.Models.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<int>("StorageLimitGB")
                        .HasColumnType("integer")
                        .HasColumnName("storage_limit_gb");

                    b.Property<int>("SubscriptionPlan")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_plan");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_organizations_owner_id");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Moondesk.Domain.Models.OrganizationMembership", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .IsRequired()
                        .HasColumnType("hstore")
                        .HasColumnName("metadata");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("UserId", "OrganizationId")
                        .HasName("pk_organization_memberships");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_memberships_organization_id");

                    b.ToTable("organization_memberships", (string)null);
                });

            modelBuilder.Entity("Moondesk.Domain.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsOnboarded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_onboarded");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .IsRequired()
                        .HasColumnType("hstore")
                        .HasColumnName("metadata");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Moondesk.Domain.Models.IoT.Alert", b =>
                {
                    b.HasOne("Moondesk.Domain.Models.IoT.Sensor", "Sensor")
                        .WithMany("Alerts")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Moondesk.Domain.Models.IoT.Command", b =>
                {
                    b.HasOne("Moondesk.Domain.Models.IoT.Sensor", "Sensor")
                        .WithMany("Commands")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commands_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Moondesk.Domain.Models.IoT.Reading", b =>
                {
                    b.HasOne("Moondesk.Domain.Models.IoT.Sensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_readings_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Moondesk.Domain.Models.IoT.Sensor", b =>
                {
                    b.HasOne("Moondesk.Domain.Models.IoT.Asset", "Asset")
                        .WithMany("Sensors")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_assets_asset_id");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Moondesk.Domain.Models.OrganizationMembership", b =>
                {
                    b.HasOne("Moondesk.Domain.Models.Organization", "Organization")
                        .WithMany("Memberships")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_organizations_organization_id");

                    b.HasOne("Moondesk.Domain.Models.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_users_user_id");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Moondesk.Domain.Models.IoT.Asset", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("Moondesk.Domain.Models.IoT.Sensor", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Commands");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("Moondesk.Domain.Models.Organization", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Moondesk.Domain.Models.User", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
